---
title: "Assignments"
---

In this course, you will write weekly summaries, a response paper to a week's readings, and a research design paper. In addition, you will serve as discussion leader for one week. You can find more information about each assignment below and in their respective pages.


## Weekly Summaries (20% of final grade)

To receive full points, you will need to write eight (8) summaries throughout the course. Since there are 13 opportunities to write a summary in the semester, you can skip five of them. The specific reading you have to summarize in any given week has a {{< fa pen >}} after it in the corresponding weekly page. It is up to you which weeks you decide to skip. The summary should not be longer than three-quarters of a page (single-spaced, 12-point font). These summaries must be submitted via Canvas prior to class on the day for which the reading is assigned. No credit will be given for submissions after class has started.

You can find a brief guide on how to write a summary [here](../resource/summaries.html).


## Response Paper (15% of final grade)

You will write a response paper (2 double-spaced pages, 12-point font) where you integrate the readings for a given week. In the response paper, you will highlight the connections between the readings, write about their applicability to current events, and offer a critique of the readings as a whole. You may choose to focus more on applicability to today or a critique of existing research. The response paper is due on the Friday of the week you choose to write on (11:59 pm deadline).


## Discussion Leader (15% of final grade)

Students will serve as discussion leaders for a portion of class time each week. At the beginning of the semester, students will choose one week where they will co-lead the discussion. You are expected to have done the readings and come up with discussion questions for the class. I encourage you to meet with me before your week to talk about the material. (P.S.: this is also a good opportunity to write your response paper since you will have read the material in more detail.)


## Research Design Paper (30% of final grade)

The research design paper is the final paper for the course. A research design paper is what we might call the "front end" of a paper. It includes the research question, the motivation, a literature review, the theory, and a strategy for how you would answer the question (i.e., the research design). While you have to specify what kind of data you would collect and how you might analyze it, you do not have to collect or analyze the data. The paper must be at least 8 pages and not more than 12 pages (double-spaced, 12-point font, 1-inch margins).

Since this is a major paper, and maybe the first time you write a paper like this, we will break down the paper into separate components as follows:

1. [Research question and list of literature](research-question.qmd) (5% of final grade)
2. [Literature review](literature-review.qmd) (5% of final grade)
3. [Theory and research design](research-design.qmd) (5% of final grade)
4. [Full research design paper](final-paper.qmd) (15% of final grade)

